---
# Task's tags
# Tags segmentation

# ansible-playbook playbook.yml --tags "install-epel"
# ansible-playbook playbook.yml --tags "install-nginx,restart-nginx"
# ansible-playbook playbook.yml --skip-tags "install-epel,install-nginx"
# ansible-playbook playbook.yml --tags "all"

- name: Install and restart nginx
  hosts: all
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        update_cache: yes
        state: latest
      become: true
      when: ansible_distribution == 'CentOS'
      tags:
        - install-epel

    - name: Install Nginx
      package:
        name: nginx
        state: latest
      become: true
      tags:
        - install-nginx

    - name: Stop apache
      service:
        name: httpd
        state: stopped
      become: true
      when: ansible_distribution == 'CentOS'
      tags:
        - restart-nginx

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      become: true
      tags:
        - restart-nginx
...
