---
# when statement (registering variable reminder)
  - hosts: all
    tasks:
      - name: Exploring register
        command: hostname -s
        when: 
          - ansible_distribution == "CentOS" 
          - ansible_distribution_major_version == "7"
        register: hostname_output 
      - name: Show register
        debug:
          msg: '{{ hostname_output }}'
...
