---
# package, service, copy modules
- name: Setup apache server and deploy the static page
  hosts: ubuntu0
  
  tasks:
    - name: Install the latest version of the apache
      package:
        name: apache2
        state: latest
      become: true

    - name: Restart the apache server
      service:
        name: apache2
        state: restarted
      become: true

    - name: Copy the index page
      copy:
        src: index.html
        dest: /var/www/html/index.html
      become: true
...
