---
# jinja condition (elif)

- hosts: all
  tasks:
    - debug:
        msg: >- 
            {% if ansible_host=="127.0.0.1" %}
            To jest Centos
            {% elif ansible_host=="127.0.0.2" %}
            To jest Ubuntu
            {% else %}
            Nie wiem co to jest
            {% endif %}
...
