---
# W scenariuszu user_setup.yml znajdują się zahardkodowane wartości
# `name`, `password', `comment` użytkownika. Zamień je na wartości
# odpowiednich zmiennych zdefiniowaych w pliku inventory.ini.

- hosts: all
  become: yes
  tasks:
    - name: Install applications
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - sqlite
        - jq
...
