---
# W scenariuszu znajdują się zahardkodowane wartości
# `name`, `password', `comment` użytkownika. Zamień je na wartości
# odpowiednich zmiennych zdefiniowaych w pliku inventory.ini.

- hosts: all
  become: yes
  tasks:
    - name: Set up user
      user:
        name: "admin"
        password: "secret_pass"
        comment: "admin@example.com"
        state: present
...
