---
# W scenariuszu znajdują się zahardkodowane wartości
# `name`, `password', `comment` użytkownika. Zamień je
# na wartości odpowiednich zmiennych zdefiniowaych
# w pliku inventory.ini.

- hosts: all
  become: yes
  tasks:
    - name: Set up user
      user:
        name: "{{ user_details.username }}"
        password: "{{ user_details.password }}"
        comment: "{{ user_details.email }}"
        state: present
...
