---
# W scenariuszu zdefiniuj 3 zmienne o zasięgu akcji `car_model`, `country_name`
# oraz `title` i użyj ich w scenariuszu w miejce zahardkodowanych wartości.

- hosts: localhost
  vars:
    car_model: 'BMW M3'
    country_name: USA
    title: 'Systems Engineer'
  tasks:
    - command: 'echo "My car is {{ car_model }}"'
    - command: 'echo "I live in the {{ country_name }}"'
    - command: 'echo "I work as a {{ title }}"'
...
