---
# user module (used three times)
- hosts: localhost
  tasks:
    - user:
        name: joe
        state: present
      become: true
    - user:
        name: george
        state: present
      become: true
    - user:
        name: bill
        state: present
      become: true
...
