---
# writting server_ip variable's value
- hosts: centos0
  vars:
    server_ip: 192.68.24.142
  tasks:
    - lineinfile:
        path: /home/ansible/test_directory/test_file.txt
        line: '{{ server_ip }}'
        create: yes
...
