---
# Scenariusz ma zdefiniowaną zmienną age oraz dwa zadania.
# Użyj dyrektywy `when`, w taki sposób żeby uruchamiany był odpowiedni
# task w zależności od wartości zmiennej `age`.

- name: 'Am I an Adult or a Child?'
  hosts: localhost
  vars:
    age: 25
  tasks:
    - name: I am a Child
      command: 'echo "I am a Child"'
      
    - name: I am an Adult
      command: 'echo "I am an Adult"'
...