---
# when statement (conditions in the form of list)
  - hosts: all
    tasks:
      - name: Exploring register
        command: hostname -s
        when: 
          - ansible_distribution == "CentOS" 
          - ansible_distribution_major_version == "7" 
...
