---
# non-existent variable foo
- hosts: centos0
  vars:
    server_ip: 192.168.24.142
  tasks:
    - lineinfile:
        path: /home/ansible/test_directory/test_file.txt
        line: 'nameserver {{ foo }}'
        create: yes
...
