---
# jinja templating: dictionary lookup
- hosts: centos0
  vars:
     dict:
       fruit: apple
       vegatable: carrot
       meat: chicken
  tasks:
    - template:
        src: example_template.j2
        dest: result.txt
...
