---
# and operator
- hosts: all
  tasks:
    - yum:
        name: net-tools
        state: latest
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
      become: true
    - apt:
        name: net-tools
        state: latest
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '22'
      become: true
...
